class BookingItem {
  int? id, washerId, status, paid, userId, packageId, serviceId = 0;
  String? date,
      time,
      total,
      paymenttype,
      duration,
      vehicletype,
      address,
      brand,
      model,
      userFirstName,
      userLastName,
      userEmail,
      userPhoneNumber,
      userVehicleNumner,
      userVehicleColor,
      packageTitle,
      packageDescription,
      packageDuration,
      packagePrice,
      serviceTitle,
      serviceDescription,
      serviceDuration,
      servicePrice,
      washerName = '';
  double lat, lng = 0.0;

  BookingItem(
      this.id,
      this.washerId,
      this.status,
      this.paid,
      this.userId,
      this.packageId,
      this.serviceId,
      this.date,
      this.time,
      this.total,
      this.paymenttype,
      this.duration,
      this.vehicletype,
      this.address,
      this.brand,
      this.model,
      this.userFirstName,
      this.userLastName,
      this.userEmail,
      this.userPhoneNumber,
      this.userVehicleNumner,
      this.userVehicleColor,
      this.packageTitle,
      this.packageDescription,
      this.packageDuration,
      this.packagePrice,
      this.serviceTitle,
      this.serviceDescription,
      this.serviceDuration,
      this.servicePrice,
      this.washerName,
      this.lat,
      this.lng);
}
